### ISSUE TITLE
No visible output to hid from libcomposite

### ISSUE THREAD

**Issue by jonfitt** [girst/hardpass-sendHID#1]
I'm configuring the driver much the same as you are (but including serial).
The serial input/output works, but I get nothing on the host when I send to the hid gadget.
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=151645

Does your USB info have the same wMaxPacketSize = 0 error that mine does?

**Comment by girst** [comment]
What OS is your host system running? Have you tried a Linux host?

Please also post your configuration script and dmesg output here.

**Comment by girst** [comment]
No response from author after >2months. closing this now.
