### ISSUE TITLE
Direct control of /dev/hidg0 doesn't work

### ISSUE THREAD

**Issue by 1dotd4** [girst/hardpass-sendHID#3]
I used your script and put it on `rc.local`.
I've first tried to use your program but it didn't work.
Then I've appended `echo -ne "\0\0\x4\0\0\0\0\0" > /dev/hidg0` to press _A_ instead of using fprintf with a compiled program and it simply doesn't do nothing... No errors just nothing.
What should I do?

Running:
 - Mac OS 10.12.x ( always updated )
 - Raspbian Jessie Lite (2016-11-25-raspbian-jessie-lite)

**Comment by 1dotd4** [comment]
When Raspberry is in hid mode I made it run `ls -la /dev/hidg0 > /home/pi/log`.
The result is `-rw-r--r-- /dev/hidg0`

**Comment by girst** [comment]
please post: 
 * `/boot/config.txt`
 * `/etc/modules`
 * `/etc/rc.local`
 * your script
 * the output of `ls -l /etc/rc.local YOUR_SCRIPT`

I currently do not have my pi with me, but I'll try to help as best as I can without it ;-)

**Comment by 1dotd4** [comment]
**BOOT**
`/boot/config.txt`
```
# For more options and information see
# http://www.raspberrypi.org/documentation/configuration/config-txt.md
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=off
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

gpu_mem=16
enable_uart=1

dtoverlay=dwc2
```

**MODULES**
`/etc/modules`
```
dwc2
g_hid
```

*RC*
`rc.local`
```
[...]
/home/pi/write
exit 0
```

**THE SCRIPT**
`/home/pi/write`
-rwxr-xr-x
```
#!/bin/bash

modprobe libcomposite
cd /sys/kernel/config/usb_gadget/
mkdir -p g1
cd g1
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
mkdir -p strings/0x409
echo "fedcba9876543210" > strings/0x409/serialnumber
echo "girst" > strings/0x409/manufacturer 
echo "Hardpass" > strings/0x409/product
N="usb0"
mkdir -p functions/hid.$N
echo 1 > functions/hid.usb0/protocol
echo 1 > functions/hid.usb0/subclass
echo 8 > functions/hid.usb0/report_length
echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.usb0/report_desc
C=1
mkdir -p configs/c.$C/strings/0x409
echo "Config $C: ECM network" > configs/c.$C/strings/0x409/configuration 
echo 250 > configs/c.$C/MaxPower 
ln -s functions/hid.$N configs/c.$C/
ls /sys/class/udc > UDC

## My code start here
echo -ne "\0\0\x4\0\0\0\0\0" > /dev/hidg0
echo -ne "\0\0\0\0\0\0\0\0" > /dev/hidg0
```

**Comment by girst** [comment]
in `/etc/modules` the `g_hid` is the old driver; remove that for a start. 

in the OP you mentioned a compiled program using printf (my `./scan`?). have you had success with that?

(again: i don't have a pi with me to check - this is a stab in the dark)

**Comment by 1dotd4** [comment]
removing `g_hid` now my pc is recognising the `Hardpass keyboard`. I used your program `./scan` but it also doesn't write nothing. I wrote a script with a loop that call your script infinitely.

```
#!/bin/bash

while [ 1 ]; do
echo "hello" | ./scan /dev/hidg0 1 0
done
```

But it still not writing nothing.

PS) note that the code is ran by the `root` user on boot.

**Comment by girst** [comment]
`/dev/hidg0` is only writeable by root; maybe that's were your problem lies?

**Comment by 1dotd4** [comment]
What do you mean? Permission on /dev/hidg0?

`ls -la /dev/hidg0 >> /home/pi/log` into rc.local:
suddenly I haven't anymore the `/dev/hidg0`, but Mac still recognising the fake keyboard.

Should I retry from zero?

**Comment by girst** [comment]
at the top of this discussion you posted this:

```
-rw-r--r-- /dev/hidg0
```

only the root user can write to `/dev/hidg0`. 

 * are you logged in as root (as opposed to `pi` or  your own name?)
 * if not, either run `sudo su`, then execute `./scan` or the `echo`-snippet
 * alternatively, do `sudo ./scan ...` and `echo echo -ne "\0\0\x4\0\0\0\0\0" | sudo tee /dev/hidg0`

**Comment by 1dotd4** [comment]
I'm connected to the pi via g_ether module so I can't use the hid directly. (I'll buy a usb console serial adapter)

I'm sure that root user run the rc.local script.

Now I'm sure that `/dev/hidg0` is:
`crw------- 1 root root 244, 0 Jan 22 14:34 /dev/hidg0`

I'm not sure if my `/boot/cmdline.txt` script is correct:
`dwc_otg.lpm_enable=0 console=tty1 console=serial0,115200 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait modules-load=dwc2`

However I've tried many combination... and now I'm not sure that rc.local is runned on boot when it is in HID mode.

**Comment by 1dotd4** [comment]
Now I'm trying to launch the script via crontab without rc.local (that seems running before the console load)

`@reboot bash /home/pi/loghid &`

**Comment by girst** [comment]
the `libcomposite` driver can handle ethernet (and usb serial) as well; you can find instructions for how to get it set up from my blog http://isticktoit.net/?p=1383 (step 1 kernel stuff is obsolete, skip it)

i do not recall modifying `cmdline.txt`; `dwc2` should be handled in `/boot/config.txt`. 

does `echo -ne "\0\0\x4\0\0\0\0\0" |sudo tee /dev/hidg0 && sleep 1 && echo -ne "\0\0\0\0\0\0\0\0" |sudo tee /dev/hidg0` send the letter 'a' to the host pc?

**Comment by 1dotd4** [comment]
Recap:
1. reflashed the iso
2. copied the script as it is from your blog (copied just the **hid** and **ether**)
3. added the script to rc.local
4. at the end of "isticktoit.sh" added:

`echo -ne "\0\0\x4\0\0\0\0\0" |sudo tee /dev/hidg0 && sleep 1 && echo -ne "\0\0\0\0\0\0\0\0" |sudo tee /dev/hidg0`

Result:

- I can ssh to the pi without `g_ether`
- Pi is not writing on the log (look at the script below)
- Pi is not writing the letter 'a' on my host pc


Actual script:

```
#!/bin/bash

cd /sys/kernel/config/usb_gadget/
mkdir -p isticktoit
cd isticktoit
echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2
mkdir -p strings/0x409
echo "fedcba9876543210" > strings/0x409/serialnumber
echo "Tobias Girstmair" > strings/0x409/manufacturer
echo "iSticktoit.net USB Device" > strings/0x409/product
mkdir -p configs/c.1/strings/0x409
echo "Config 1: ECM network" > configs/c.1/strings/0x409/configuration
echo 250 > configs/c.1/MaxPower
# Add functions here

mkdir -p functions/ecm.usb0
# first byte of address must be even
HOST="48:6f:73:74:50:43" # "HostPC"
SELF="42:61:64:55:53:42" # "BadUSB"
echo $HOST > functions/ecm.usb0/host_addr
echo $SELF > functions/ecm.usb0/dev_addr
ln -s functions/ecm.usb0 configs/c.1/

mkdir -p functions/hid.usb0
echo 1 > functions/hid.0/protocol
echo 1 > functions/hid.0/subclass
echo 8 > functions/hid.0/report_length
echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > functions/hid.0/report_desc
ln -s functions/hid.usb0 configs/c.1/

# End functions
ls /sys/class/udc > UDC

ifconfig usb0 10.0.0.1 netmask 255.255.255.252 up
route add -net default gw 10.0.0.2

#sleep 1

#echo -ne "\0\0\x4\0\0\0\0\0" > /dev/hidg0 #press the A-button
#echo -ne "\0\0\0\0\0\0\0\0" > /dev/hidg0 #release all keys

sleep 1

echo -ne "\0\0\x4\0\0\0\0\0" |sudo tee /dev/hidg0 && sleep 1 && echo -ne "\0\0\0\0\0\0\0\0" |sudo tee /dev/hidg0

date >> /home/pi/gol
ls -la /dev/hidg0 >> /home/pi/gol
```

**Comment by girst** [comment]
remove that line i gave you from the script. ssh into the pi and run it manually.

**Comment by 1dotd4** [comment]
it doesn't do nothing.

**Comment by girst** [comment]
anything on the terminal? dmesg?

**Comment by 1dotd4** [comment]
no, and I think there is another problem: my host pc doesn't recognise the keyboard.

**Comment by 1dotd4** [comment]
what should there be into `/etc/modules`?

**Comment by girst** [comment]
windows? because microsoft doesn't ship libcomposite drivers. (which i probably should add to the repo's readme -- i mentioned it in the blog post)

**Comment by 1dotd4** [comment]
mac os sierra 10.12.2

**Comment by 1dotd4** [comment]
but as i sad before it was recognising it

**Comment by girst** [comment]
regarding your older post: /etc/modules should have 
```
dwc2
libcomposite
```

inside (or you can load them with `modprobe`, shouldn't matter. 

i have never touched a mac in my life, so that's the end of my wisdom i guess unfortunately. it works for me™, so maybe try to get it running on a linux pc first? (maybe the mac driver doesn't like multiple emulated devices?)

**Comment by girst** [comment]
also, disregard my comment on ignoring the step 1 kernel stuff. ignore the line `sudo BRANCH=next rpi-update`, but do everything else.

**Comment by 1dotd4** [comment]
yes I never ran that command

**Comment by 1dotd4** [comment]
Connected to Win 7 and doesn't work. (driver issue)

**Comment by girst** [comment]
your prolem seems to be somewhere other than my `./scan`, so i'll close that issue. sorry i couldn't help

**Comment by yours-fusky** [comment]
Hi, not opening new one as I have the same issue. Except I don`t need the ether module, just hid. Tried Linux and Windows as hosts, but it is not recognizing the device as keyboard. The echo, nor scan example works for me.

I'm currently using:
`Linux raspberrypi 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux`

**Comment by yours-fusky** [comment]
I kinda found what is going on...

This line resolves in segmentation fault on newer kernels
`ls /sys/class/udc > UDC`

When I downgraded to 4.4.49, it works like a charm. 

Anyway I would like to find out how to make it work on new versions but this is okay for me now
