### ISSUE TITLE
Question: How to send a return?

### ISSUE THREAD

**Issue by nmaas87** [girst/hardpass-sendHID#4]
Hello there, great software!
Just a quick question: How to send a linebreak / return to a windows machine?
I tried several things like echo "\n" and such, but did not get it working.

Thanks a lot!

**Comment by girst** [comment]
wow, what an oversight on my end. i currently don't have my pi with me, but i have pushed a new version of the code to the `devel` branch.  

could you please try this one out for me? (sending `\t` and `\n` should work now)

**Comment by nmaas87** [comment]
@girst Thank you very much, I am on the road at the moment - but I will be back in 4 hours and test - and report back 👍

**Comment by nmaas87** [comment]
Thank you very much, just piping in echo (without -n ;)) worked a treat in the devel version, also sending \t and \n with echo -e worked :)! So I think you can merge the changes - thanks a lot for your fast help and kudos for the awesome program - I really needed to write some text down via HID from a usb gadget - and your code makes it so much easier to do that :)! You can close the question anytime :)
