### ISSUE TITLE
I am having trouble printing the letter "g"

### ISSUE THREAD

**Issue by NicholasJCameron** [girst/hardpass-sendHID#5]
Any idea whats going on with the letter g also 0X0A? is it conflicting with nl ? any work arounds or insight?

**Comment by girst** [comment]
Hi, this mail got drowned (sorry). 

What exactly is your problem? does it still persist or where you able to solve it (if so, how)?

**Comment by NicholasJCameron** [comment]
bin/echo

**Comment by girst** [comment]
have you sent your mail off too early?
