### ISSUE TITLE
how to emulate mouse?

### ISSUE THREAD

**Issue by keithkim** [girst/hardpass-sendHID#8]
Very nice project.  Followed your blog and works well.  But it's missing emulating mouse.  I understand this git repo has code for emulating key strokes, but would you know how to emulate mouse movement?  Thanks.

**Comment by girst** [comment]
hi, i don't have looked into mouse movements. this should technically be
possible by the libcomposite driver, but it's out of scope for this
pro{gram,ject}.

**Comment by nonstop99** [comment]
Hi,

I'm also looking for an easy way to move the mouse, there seems to be very few examples on the net. 

I found these pages that might be helpful tho...

https://translate.google.com/translate?depth=1&hl=en&prev=search&rurl=translate.google.com&sl=ko&sp=nmt4&u=https://www.sysnet.pe.kr/2/0/11364&xid=25657,15700023,15700186,15700190,15700253,15700256,15700259

https://translate.google.com/translate?depth=1&hl=en&prev=search&rurl=translate.google.com&sl=ko&sp=nmt4&u=https://www.sysnet.pe.kr/2/0/11369&xid=25657,15700023,15700186,15700190,15700253,15700256,15700259

**Comment by girst** [comment]
Great find! I've archived these pages, in case they go down here:

https://web.archive.org/web/20190509205509/https://www.sysnet.pe.kr/2/0/11369 
https://web.archive.org/web/20190509205505/https://www.sysnet.pe.kr/2/0/11364

**Comment by keithkim** [comment]
Thanks. I actually found the same pages and configured it.  Works well.

**Comment by nonstop99** [comment]
ah no way! legend, 

can you post the code?

is it possible to get the mouse position? or move it relatively?

**Comment by keithkim** [comment]
I didn’t integrated with the code in this repo though.  I modified some
other code.

I can move the mouse cursor in relative position.  I believe it is possible
to move it by absolute position but that involves getting host machine’s
screen dimension.

I have the test code around some where on my home PC.  I’ll post it when I
have the time but basically it’s just following the steps of the blog page.
Nothing special.

**Comment by nonstop99** [comment]
thanks Keith,

I want to move the mouse to specific x,y coordinates, I guess the only way of doing this is to somehow get the current x,y position of the mouse?

Cheers

**Comment by nonstop99** [comment]
Help!

i'm stuck, my Pi Zero arrived to day and i've set the pi up as a mouse, but how do I send commands from the command line or python to move the mouse?
